server:
  port: ${USER_SERVICE_PORT}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  flyway:
    baseline-version: 1.0
    clean-disabled: true
    validate-on-migrate: true
    out-of-order: false
    enabled: true

  application:
    name: USER-SERVICE-BACKEND

  rabitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: ${JWT_EXPIRATION}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    appname: USER-SERVICE-BACKEND