services:
    rabbit-mq:
      image: "rabbitmq:3-management"
      container_name: rabbitmq_screener
      ports:
        - "5672:5672"
        - "15672:15672"
      networks:
        - screener

volumes:
  postgres_data:

networks:
  screener:
    driver: bridge