server:
  port: 8085

spring:
  application:
    name: screener-ms-api-gateway

  cloud:
    gateway:
#      mvc:
      routes:
        - id: fraud-detection-service
          uri: lb://FRAUD-DETECTION-SERVICE-BACKEND
          predicates:
            - Path=/api/v1/fraud/**
          filters:
            - AuthenticationFilter

        - id: screener-service
          uri: lb://SCREENER-SERVICE-BACKEND
          predicates:
            - Path=/api/v1/screener/**
          filters:
            - AuthenticationFilter

        - id: user-service
          uri: lb://USER-SERVICE-BACKEND
          predicates:
            - Path=/api/v1/auth/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

